z_positions = [ 0.0, 1.5, 3.0, 4.5, 6.0, 7.5, 9.0, 10.5 ]
exposure_time = 0.1

[ilm750]
power = 10
sequence = [ 0, 0, 0, 0, 0, 0, 0, 0 ]

[ilm650]
power = 10
sequence = [ 0, 0, 0, 0, 0, 0, 0, 0 ]

[ilm560]
power = 80
sequence = [ 0, 1, 1, 1, 1, 1, 1, 1 ]

[ilm488]
power = 10
sequence = [ 1, 0, 0, 0, 0, 0, 0, 0 ]

[ilm405]
power = 10
sequence = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
